### ISSUE TITLE
Documentation of external_tools

### ISSUE THREAD

**Issue by zlskidmore** [ikalatskaya/ISOWN#1]
Hi,

when running your command I received the following error:

```
annotating input file with ANNOVAR ...Can't open perl script "~/software/ISOWN/bin/../external_tools/annovar_2012-03-08/annotate_variation.pl": No such file or directory
```

I assume I need to download annovar and put it in that directory,but it might be good to document that, or add annovar to the list of dependencies on the README

**Comment by qtrinh** [comment]
As suggested, we added ANNOVAR as a dependency in the README file.  Thank you.
