### ISSUE TITLE
Error in cosmic_format_index.pl with absolute paths

### ISSUE THREAD

**Issue by lpalomerol** [ikalatskaya/ISOWN#11]
Hello, I've been trying to run this perl program and I've found one error when running it using absoblute paths 

This is the command I've performed:

`
     perl /home/idibell/opt/ISOWN/bin/cosmic_format_index.pl \
        ~/opt/ISOWN/external_databases/CosmicCodingMuts.vcf.gz  \
        ~/opt/ISOWN/external_databases/CosmicNonCodingVariants.vcf.gz 
`

The error appears at combine headers step and is a "file not found error", this is the error trace:

`
"Combine headers ...cat: **_/home/idibell/opt/ISOWN/external_databases/CosmicCodingMuts.vcf.gz.header:** No existe el fichero o el directorio
cat: _/home/idibell/opt/ISOWN/external_databases/CosmicNonCodingVariants.vcf.gz.header: No existe el fichero o el directorio
"
`

I've checked the code and the origin of this error are the zcat outputs, you are adding an underscore in the begin of the file location, and chrashes when the file is an absolute path

`

printf "\nExtract headers from ${CODING_FILE} and ${NON_CODING_FILE}  ...";

system "zcat $CODING_FILE  | head -500  | grep \"^#\" | grep -v CHROM > _${CODING_FILE}.header";

system "zcat $NON_CODING_FILE  | head -500  | grep \"^#\" > _${NON_CODING_FILE}.header";
`

Regards,
Luis.

**Comment by qtrinh** [comment]
Hi Luis
  We have updated cosmic_format_index.pl to support absolute path.  Thanks for letting us know.

Q

**Comment by lpalomerol** [comment]
You are welcome!
