### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by lpalomerol** [ikalatskaya/ISOWN#12]
Hello again,

Mutation Accessor MA.scores.hg19.tar.bz2 link is outdated. Now they are working with version 3, and I think the equivalent file is at "http://mutationassessor.org/r3/MA_scores_rel3_hg19_full.tar.gz" path.

Regards,
L

**Comment by qtrinh** [comment]
Thanks very much.  We will do a test to ensure Mutation Accessor release version 3 works with our ISOWN pipeline.  We will update the document afterward.

Q

**Comment by lpalomerol** [comment]
:smile: 

You are welcome

**Comment by djamgo88** [comment]
any updates?
