### ISSUE TITLE
mutation taser file not available

### ISSUE THREAD

**Issue by sasi-arunachalam** [ikalatskaya/ISOWN#14]
I found an issue and trying to fix it. Please let me know if I am right.

MA.scores.hg19.tar.bz2 is not available anymore. They have released MA_scores_rel3_hg19_full.tar (rel 3).  Upon unzipping the files there are many csv files under the folder MA_scores_rel3_hg19_full

Then:
Reformat and index Mutation Assessor by using the following script:
perl ${ISOWN_HOME}/bin/mutation-assessor_format_index_vcf.pl MA_scores_rel3_hg19_full 2013_12_11_MA.vcf 

does your perl code works for the new release? ( I never done perl before)

Thanks
Sasi

**Comment by sasi-arunachalam** [comment]
It worked.

**Comment by Flope** [comment]
The readme doc indicates the following:
wget http://mutationassessor.org/r3/MA_scores_rel3_swissprot_full.tar.gz --no-passive-ft
but as it is mentioned here, it should be this one, right?
 wget http://mutationassessor.org/r3/MA_scores_rel3_hg19_full.tar.gz

**Comment by groadabike** [comment]
> The readme doc indicates the following: wget http://mutationassessor.org/r3/MA_scores_rel3_swissprot_full.tar.gz --no-passive-ft but as it is mentioned here, it should be this one, right? wget http://mutationassessor.org/r3/MA_scores_rel3_hg19_full.tar.gz

@Flope, thank you for your comment, It was very helpfull.
I found the documentation of this program very frustrating.

**Comment by Flope** [comment]
I managed to get the whole thing working but I don't recommend it. 
You will need to figure out every step pretty much and you can see how much they are supporting it here.
I run a couple of datasets with ISOWN and GATK with the Panel of Normals. 
There is barely any overlap. GATK definitely has a lot of false positives but ISOWN only outputted a few variants with a 1 or 2 of them overlapping with GATK,

**Comment by RieLuc23** [comment]
So link is apparently dead....
wayback machine has only one snapshot and it is corrupted....
wget -c https://web.archive.org/web/20160802103335/http://mutationassessor.org/r3/MA_scores_rel3_hg19_full.tar.gz

Any solution on how to get that file?
