### ISSUE TITLE
databases in database_annotation.pl do not match README

### ISSUE THREAD

**Issue by zlskidmore** [ikalatskaya/ISOWN#2]
Hi,

lines 14-19 of database_annotation.pl do not currently match the README docs, for example ExAC is:
```perl
my $ExAC="$cwd/../external_databases/ExAC.r0.3.sites.vep.vcf.20150421.vcf.gz";
```
but should be:

```perl
my $ExAC="$cwd/../external_databases/ExAC.r0.3.1.database.vcf";
```

if following the example from the README I think. Maybe these paths should not be hardcoded or if so the format_index commands should name the files themselves instead of the user?

Also the following file ../external_databases/hg19_random.fa does not exist (line 14), And is not mentioned in the docs as far as I could tell, Is this the entire hg19 build assembly?

**Comment by qtrinh** [comment]
Hi @zlskidmore 
  Thank you for your comments.  We will look at these shortly.

Q

**Comment by qtrinh** [comment]
Corrected file name for ExAC database in  database_annotation.pl.  
 Yes, hg19_random.fa is the entire hg19 build assembly.  We added information on how and where to downloaded hg19 build assembly.  Thank you,
