### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by genowis123** [ikalatskaya/ISOWN#3]
Hi

when i run programming,error occur. could you tell me why? 

qpipeline tabix -m 2021 -d /mnt/sdb/ISOWN1/ISOWN/external_databases/COSMIC_v69.vcf.gz -A -E -p COSMIC_v69 -i  test.vcf.temp.annovar.vcf -f /mnt/sdb/ISOWN1/ISOWN/external_databases/hg19_random/genome.fa > db.vcf
Segmentation fault

**Comment by genowis123** [comment]
ok, I anwser the qusetion by myself.  you can set (ulimit -s 65536) on linux

**Comment by chungtseng** [comment]
Hi, 
I ran into a permission deny error triggered by qpipeline. I have module load all the dependencies and set the PATH as well. 

/ISOWN/bin/qpipeline tabix -m 2020 -d /ISOWN/bin/../external_databases/MA.release2.vcf.gz -A -E -p 2013_12_11_MA -i 519b8381-95d5-4fce-a90c-7576cce2110c.dkfz-snvCalling_1-0-132-1.20160126.vcf.temp.exac.vcf  -f /ISOWN/bin/../external_databases/hg19_random.fa > 519b8381-95d5-4fce-a90c-7576cce2110c.dkfz-snvCalling_1-0-132-1.20160126.vcf.temp.ma.vcfsh: /ISOWN/bin/qpipeline: Permission denied
I also tried the qpipeline tool separately and have problem compiling the qpipeline.

**Comment by qtrinh** [comment]
Let us know if you have any other questions.  Thanks.

**Comment by EgirardBioinfo** [comment]
Hi, 
I have the same segmentation fault but do not have root options to change ulimit. Could you provide a solution for that ? I can't create any db you require to run ISOWN. Thanks,
