### ISSUE TITLE
Tabix fails to index Mutation Accessor VCF file

### ISSUE THREAD

**Issue by rnaplus** [ikalatskaya/ISOWN#4]
In the file "bin/mutation-assessor_format_index_vcf.pl", change the following line:  
`system "bgzip $OUTPUT_FILE  ; tabix -s 1 -b 2 -e 3 ${OUTPUT_FILE}.gz";`
to  
`system "bgzip $OUTPUT_FILE  ; tabix -p vcf ${OUTPUT_FILE}.gz";`  
  
Edit: `tabix` command also needs to be changed in the "bin/polyphen-whess_format_index.pl" file

**Comment by qtrinh** [comment]
Done.  Thank you,

**Comment by qtrinh** [comment]
Changes made as suggested by @rnaplus.
