### ISSUE TITLE
nobody test this software?

### ISSUE THREAD

**Issue by WinterLi1993** [ikalatskaya/ISOWN#5]
HI,
   I found there is no any issues about this software , sorry , it's not good ?

**Comment by qtrinh** [comment]
Hi,
  We had a few issues reported both here and via emails, in which we addressed them all.   Feel free to try it out and send us emails or create your tickets here.  

Thanks 

Q

**Comment by WinterLi1993** [comment]
@qtrinh 
could you please tell me your e-mail address ?

**Comment by qtrinh** [comment]
Hi 
  You can send us email at  ikalats@gmail.com and quang.trinh@gmail.com 

Thanks,

Q

**Comment by qtrinh** [comment]
closing ticket.
