### ISSUE TITLE
Mutation assessor link is dead

### ISSUE THREAD

**Issue by berguner** [ikalatskaya/ISOWN#6]
Hello,

I am trying to setup all the dependencies. The link for downloading the mutation assessor scores is not working. I downloaded the rel3 version `http://mutationassessor.org/r3/MA_scores_rel3_hg19_full.tar.gz` but the perl script did not work with this version. Can you please fix this issue?

Best,
Bekir

**Comment by qtrinh** [comment]
Hi 
  MutationAssessor changed its format in release 3 so that's why our script broke.  We fixed bin/mutation-assessor_format_index_vcf.pl to work with release 3.   Please do git pull and try again and let us know if have any issues.

Q

**Comment by berguner** [comment]
Thanks Q, the fix worked with r3.

**Comment by genome1** [comment]
Please fix the instruction section for MutationAssessor, as the download link http://mutationassessor.org/v1/ for the software does not work any more and the scores have been updated to release 3.
