### ISSUE TITLE
Segmentation fault (core dumped) error

### ISSUE THREAD

**Issue by AkankshaFarswan** [ikalatskaya/ISOWN#9]
Hi I got the following error when i tried to annotate test data file provided in the test_data folder. How can I resolve it?

annotating input file with ANNOVAR ...NOTICE: Output files were written to test1data_final.temp.annovar.vcf.temp.convert2annovar.variant_function, test1data_final.temp.annovar.vcf.temp.convert2annovar.exonic_variant_function
NOTICE: Reading gene annotation from /home/akanksha/Documents/ISOWN/bin/../external_tools/annovar_2012-03-08/humandb/hg19_refGene.txt ... Done with 63481 transcripts (including 15216 without coding sequence annotation) for 27720 unique genes
NOTICE: Processing next batch with 40066 unique variants in 40066 input lines
NOTICE: Reading FASTA sequences from /home/akanksha/Documents/ISOWN/bin/../external_tools/annovar_2012-03-08/humandb/hg19_refGeneMrna.fa ... Done with 18834 sequences
WARNING: A total of 405 sequences will be ignored due to lack of correct ORF annotation

/home/akanksha/Documents/ISOWN/bin/qpipeline tabix -m 2020 -d /home/akanksha/Documents/ISOWN/bin/../external_databases/00-All.modified.vcf.gz -A -E -p dbSNP142_All_20141124 -i test1data_final.vcf.temp.annovar.vcf  -f /home/akanksha/Documents/ISOWN/bin/../external_databases/hg19_random.fa > test1data_final.vcf.temp.dbSNP.vcfSegmentation fault (core dumped)

annotating input file with COSMIC ...

/home/akanksha/Documents/ISOWN/bin/qpipeline tabix -m 2020 -d /home/akanksha/Documents/ISOWN/bin/../external_databases/CosmicAll.gz -A -E -p COSMIC_69 -i test1data_final.vcf.temp.dbSNP.vcf  -f /home/akanksha/Documents/ISOWN/bin/../external_databases/hg19_random.fa > test1data_final.vcf.temp.cosmic.vcfSegmentation fault (core dumped)

annotating input file with ExAC ...

/home/akanksha/Documents/ISOWN/bin/qpipeline tabix -m 2020 -d /home/akanksha/Documents/ISOWN/bin/../external_databases/ExAC.r0.3.1.database.vcf.gz -A -E -p ExAC.r0.3_20150421 -i test1data_final.vcf.temp.cosmic.vcf  -f /home/akanksha/Documents/ISOWN/bin/../external_databases/hg19_random.fa > test1data_final.vcf.temp.exac.vcfSegmentation fault (core dumped)

annotating input file with MutationAccessor ...

/home/akanksha/Documents/ISOWN/bin/qpipeline tabix -m 2020 -d /home/akanksha/Documents/ISOWN/bin/../external_databases/2013_12_11_MA.vcf.gz -A -E -p 2013_12_11_MA -i test1data_final.vcf.temp.exac.vcf  -f /home/akanksha/Documents/ISOWN/bin/../external_databases/hg19_random.fa > test1data_final.vcf.temp.ma.vcfSegmentation fault (core dumped)

nnotating input file with PolyPhen ...

annotating input file with sequence context ...

calculating flanking region ...Segmentation fault (core dumped)

final reformatting ...Segmentation fault (core dumped)

cleanup: deleting temporary files ( test1data_final.vcf*.temp.* ) ...

**Comment by qtrinh** [comment]
Hi 
  can you run the following command and send us your output:

/home/akanksha/Documents/ISOWN/bin/qpipeline tabix -m 2020 -d /home/akanksha/Documents/ISOWN/bin/../external_databases/00-All.modified.vcf.gz -A -E -p dbSNP142_All_20141124 -i test1data_final.vcf.temp.annovar.vcf -f /home/akanksha/Documents/ISOWN/bin/../external_databases/hg19_random.fa -v >test1data_final.vcf.temp.cosmic.vcf

(I added -v to your command for verbose output ).

Thanks
